version: "3"

services:
  pi_cam_env_sensors:
    container_name: pi_cam_env_sensors
    hostname: ${HOSTNAME}
    image: pi_cam_env_monitor:latest
    env_file: .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/i2c-0
      - /dev/i2c-1
      - /dev/i2c-10
      - /dev/i2c-20
      - /dev/i2c-21
      - /dev/i2c-22
    restart: unless-stopped
